config/routes.rb
Protocolonel::Application.routes.draw do
  resources :protocols
  
  root :to => 'protocols#index'

end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :bootstrap_backbone
  
  private
  def bootstrap_backbone
    @_protocols ||= Protocol.all
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  # GET /protocols
  # GET /protocols.json
  def index
    @protocols = Protocol.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @protocols }
    end
  end

  # GET /protocols/1
  # GET /protocols/1.json
  def show
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @protocol }
    end
  end

  # GET /protocols/new
  # GET /protocols/new.json
  def new
    @protocol = Protocol.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @protocol }
    end
  end

  # GET /protocols/1/edit
  def edit
    @protocol = Protocol.find(params[:id])
  end

  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = Protocol.new(params[:protocol])

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocol was successfully created.' }
        format.json { render json: @protocol, status: :created, location: @protocol }
      else
        format.html { render action: "new" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /protocols/1
  # PUT /protocols/1.json
  def update
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      if @protocol.update_attributes(params[:protocol])
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocols/1
  # DELETE /protocols/1.json
  def destroy
    @protocol = Protocol.find(params[:id])
    @protocol.destroy

    respond_to do |format|
      format.html { redirect_to protocols_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Protocolonel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="app">

<%= yield %>

</div>

<%= javascript_tag do %>
  if (typeof Protocolonel != 'undefined') {
    Protocolonel.init(<%= @_protocols.to_json.html_safe %>);
  }
<% end %>

</body>
</html>

app/views/protocols/_form.html.haml
= form_for @protocol do |f|
  -if @protocol.errors.any?
    #error_explanation
      %h2= "#{pluralize(@protocol.errors.count, "error")} prohibited this protocol from being saved:"
      %ul
        - @protocol.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/protocols/edit.html.haml
%h1 Editing protocol

= render 'form'

= link_to 'Cancel', protocol_path(@protocol)

app/views/protocols/index.html.erb
<h1>Listing protocols</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @protocols.each do |protocol| -%>
      <tr id ="protocol_<%= protocol.id %>">
        <td><%= protocol.name %></td>
        <td><%= link_to 'Show', protocol %></td>
        <td><%= link_to 'Edit', edit_protocol_path(protocol) %></td>
        <td><%= link_to 'Destroy', protocol, :method => :destroy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Protocol', new_protocol_path %>

app/views/protocols/new.html.haml
%h1 New protocol

= render 'form'

= link_to 'Back', protocols_path

app/views/protocols/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @protocol.name
%p
  %b Body:
  = @protocol.body

= link_to 'Edit', edit_protocol_path(@protocol)
\|
= link_to 'Back', protocols_path